### ISSUE TITLE
Support scala.js

### ISSUE THREAD

**Issue by gjuhasz86** [scala/scala-collection-contrib#113]
It would be good to make these classes available in scala.js.

**Comment by SethTisue** [comment]
Ah, I see we published for Scala.js 1.0.0-RC2 but then never for any newer version.

Sure, I can pull the publishing lever this week.

**Comment by SethTisue** [comment]
A note on semantic versioning:

0.2.1 should have been 0.3.0, since it had real additions and not just bug fixes.

But what about this time around? This time we only have a single bugfix (#86) and no other user-visible changes.

I'm a bit tempted to go 0.3.0 as a way of sort of retroactively correcting the 0.2.1 mistake, but it probably makes more sense to call this one 0.2.2, but mention the mistake in the release notes, and then hopefully we won't forget next time.

**Comment by SethTisue** [comment]
Release job https://travis-ci.com/github/scala/scala-collection-contrib/builds/193055006

I hit "release" on the staging repos in the Sonatype web UI. Artifacts should be on their way to Maven Central. Keeping the ticket open until I've verified they've arrived.
